# Generated by Django 3.2 on 2022-03-02 08:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_product_category_image_path),
        ),
    ]
