# Generated by Django 3.2 on 2022-03-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='location',
            new_name='location1',
        ),
    ]
