export enum ActionTypes {
	SET_THEME = "SET_THEME",

	// auth
	USER_LOGIN = "USER_LOGIN",
	USER_LOGOUT = "USER_LOGOUT",
	AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS",
	AUTH_USER_ERROR = "AUTH_USER_ERROR",
	AUTH_USER_LOADING = "AUTH_USER_LOADING",

	// products
	SET_CATEGORY = "SET_CATEGORY",
	CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS",
	CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR",

	PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
	PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR",
	PRODUCT_LIST_LOADING = "PRODUCT_LIST_LOADING",

	PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS",
	PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR",
	PRODUCT_DETAIL_LOADING = "PRODUCT_DETAIL_LOADING",

	USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS",
	USER_DETAIL_ERROR = "USER_DETAIL_ERROR",
	USER_DETAIL_LOADING = "USER_DETAIL_LOADING",

	GET_CART_SUCCESS = "GET_CART_SUCCESS",

	USER_ADDRESS_LOADING = "USER_ADDRESS_LOADING",
	USER_ADDRESS_ERROR = "USER_ADDRESS_ERROR",
	USER_ADDRESS_LIST = "USER_ADDRESS_LIST",
	USER_ADDRESS_SELECTED = "USER_ADDRESS_SELECTED",
	USER_ADDRESS_CREATE = "USER_CREATERESS_CREATE",
	USER_ADDRESS_DELETE = "USER_CREATERESS_DELETE",

	USER_ORDER_LOADING = "USER_ORDER_LOADING",
	USER_ORDER_ERROR = "USER_ORDER_ERROR",
	USER_ORDER_LIST = "USER_ORDER_LIST",
	USER_ORDER_CREATE = "USER_ORDER_CREATE",
}
